---
- name: Configure my remote Desktop
  hosts:
    - debidesk

  vars:
    use_handlers: 'true'
    use_reboot: 'false'
    use_logout: 'false'

  tasks:

    - name: Setup user account
      include_role:
        name: useraccount

    - name: Shell Tools
      block:

        - name: Install shell tools
          package:
            name:
              - vim
              - htop
              - curl
              - mc
              - screen
              - git
              - ncdu
              - wget
              - less
              - nmap
              - mtr
              - parted
              - dosfstools
              - btrfs-progs
              - exfatprogs
              - ntfs-3g
              - xfsprogs
              - gpart
              - unp
              - unrar
              - unzip
              - bzip2
              - p7zip
              - unace
              - cpio
              - sharutils
              - cabextract

        - name: Create vimrc
          copy:
            dest: /root/.vimrc
            owner: root
            group: root
            mode: u=rw,go=-
            content: |
              set background=dark
              syntax on
              set mouse=

    - name: Prevent network-manager from being installed
      copy:
        dest: /etc/apt/preferences.d/10-no-network-manager.pref
        owner: root
        group: root
        mode: u=rw,go=r
        content: |
          Package: network-manager
          Pin: release *
          Pin-Priority: -1

    - name: Install desktop
      package:
        name:
          - gnome
          - xrdp
          - fonts-recommended

    - name: Enable and start xrdp
      systemd_service:
        name: xrdp
        enabled: true
        state: started

    - name: Disable lightdm
      systemd_service:
        name: gdm
        enabled: false
        state: stopped

    - name: Finish Setup
      block:

        - name: Disable automatic ansible apply service
          systemd_service:
            name: perrys-ansible-apply
            enabled: false

        - name: Trigger handlers
          ansible.builtin.meta: flush_handlers

        - name: Reboot
          shell:
            executable: /usr/bin/bash
            cmd: reboot
          when: use_reboot | bool
