---
- name: Configure my remote Desktop
  hosts:
    - debidesk

  vars:
    use_handlers: 'true'
    use_reboot: 'false'
    use_logout: 'false'

  tasks:

    - name: Setup user account
      include_role:
        name: useraccount

    - name: Setup swap space
      include_role:
        name: swapfilesetup

    - name: Self-Signed cert
      include_role:
        name: selfsignedcert

    - name: Shell Tools
      block:

        - name: Install shell tools
          package:
            name:
              - vim
              - htop
              - curl
              - mc
              - screen
              - git
              - ncdu
              - wget
              - less
              - nmap
              - mtr
              - parted
              - dosfstools
              - btrfs-progs
              - exfatprogs
              - ntfs-3g
              - xfsprogs
              - gpart
              - unp
              - unrar
              - unzip
              - bzip2
              - p7zip
              - unace
              - cpio
              - sharutils
              - cabextract

        - name: Create vimrc
          copy:
            dest: /root/.vimrc
            owner: root
            group: root
            mode: u=rw,go=-
            content: |
              set background=dark
              syntax on
              set mouse=

    - name: Install desktop
      package:
        name:
          - kde-full
          #- kde-standard
          - python3-firewall
          - pipewire
          - fonts-recommended
          - firefox-esr
          - firefox-esr-l10n-de
          - thunderbird
          - thunderbird-l10n-de
          - seafile-gui
          - nextcloud-desktop
          - keepass2
          - handbrake
          - libreoffice
          - libreoffice-l10n-de
          - transmission-qt

    - name: Configure XRDP
      include_role:
        name: xrdpsetup

    - name: Open SSH Port
      ansible.posix.firewalld:
        port: 22/tcp
        permanent: true
        state: enabled

    - name: Open RDP Port
      ansible.posix.firewalld:
        port: 3389/tcp
        permanent: true
        state: enabled

    - name: Configure perrys-ansible-apply
      include_role:
        name: applyscriptsetup

    - name: Finish Setup
      block:

        - name: Trigger handlers
          ansible.builtin.meta: flush_handlers

        - name: Reboot
          shell:
            executable: /usr/bin/bash
            cmd: reboot
          when: use_reboot | bool
