---
- name: Keyboard experiments
  hosts: all

  tasks:

    - apt:
        state: "{{item[0]}}"
        purge: "{{item[1]}}"
        name:
          - locales
          - keyboard-configuration
          - console-setup
          - tzdata
      loop:
        - [ absent, true ]
        - [ present, false ]

    - name: Set timezone
      timezone:
        name: "{{timezone}}"

    - name: Set locale
      locale_gen:
        name: "{{item}}"
      loop: "{{locales}}"

    - name: Debconf for Ubuntu/Debian systems
      debconf:
        name: "{{item[0]}}"
        question: "{{item[1]}}"
        vtype: "{{item[2]}}"
        value: "{{item[3]}}"
        unseen: true
      loop:
        - [ 'console-setup', 'console-setup/charmap47', 'select', 'UTF-8' ]
        - [ 'console-setup', 'console-setup/codeset47', 'select', '# Latin1 and Latin5 - western Europe and Turkic languages' ]
        - [ 'console-setup', 'console-setup/fontface47', 'select', 'VGA' ]
        - [ 'console-setup', 'console-setup/fontsize', 'select', '8x16' ]
        - [ 'keyboard-configuration', 'keyboard-configuration/altgr', 'select', 'Right Alt (AltGr)' ]
        - [ 'keyboard-configuration', 'keyboard-configuration/compose', 'select', 'No compose key' ]
        - [ 'keyboard-configuration', 'keyboard-configuration/ctrl_alt_bksp', 'boolean', 'false' ]
        - [ 'keyboard-configuration', 'keyboard-configuration/layout', 'select', '{{debconfkeymap}}' ]
        - [ 'keyboard-configuration', 'keyboard-configuration/model', 'select', 'Generic 105-key PC' ]
        - [ 'keyboard-configuration', 'keyboard-configuration/variant', 'select', '{{debconfkeymapvariant}}' ]
        - [ 'locales', 'locales/default_environment_locale', 'select', '{{locale}}' ]
        - [ 'locales', 'locales/locales_to_be_generated', 'multiselect', "{{locales|join(' UTF-8, ')}} UTF-8" ]
        - [ 'tzdata', 'tzdata/Zones/Etc', 'select', '{{timeregion}}' ]
        - [ 'tzdata', 'tzdata/Zones/{{timeregion}}', 'select', '{{timecity}}' ]

    - name: Run dpkg-reconfigure
      shell:
        chdir: /
        executable: /bin/bash
        cmd: 'dpkg-reconfigure -fnoninteractive {{item}}'
      loop:
        - keyboard-configuration
        - console-setup
        - locales
        - tzdata
      register: reconf

    - debug:
        var: reconf
