---
- name: Setup my old retired laptop
  hosts: all

  tasks:

    - name: add hosts to inventory groups
      add_host:
        name: "{{ inventory_hostname }}"
      changed_when: False

    - name: Install required packages
      package:
        name: parted

    - name: Create swap partition
      parted:
        device: "{{disk}}"
        label: gpt
        part_type: primary
        number: 1
        name: swap
        fs_type: linux-swap
        part_end: 8GiB
        state: present
      register: swappart

    - name: Create root partition
      parted:
        device: "{{disk}}"
        label: gpt
        part_type: primary
        number: 2
        name: root
        flags: [ boot ]
        fs_type: ext4
        part_start: 8GiB
        part_end: 100%
        state: present
      register: rootpart

    - debug:
        var: swappart

    - debug:
        var: rootpart
