---
- name: Setup my old retired laptop
  hosts: archiso

  tasks:

    - name: Set timezone
      timezone:
        name: Europe/Berlin

    - name: Set locale
      locale_gen:
        name: en_US.UTF-8

    - name: Install required packages
      package:
        name: "{{item}}"
      loop:
        - parted
        - bash

    # - name: Create swap partition
    #   parted:
    #     device: "{{disk}}"
    #     label: gpt
    #     number: 1
    #     name: swap-svrlsiac
    #     part_end: 8GiB
    #     state: present

    # - name: Format swap partition
    #   filesystem:
    #     dev: /dev/disk/by-partlabel/swap-svrlsiac
    #     fstype: swap
    #     force: true

    - name: Create root partition
      parted:
        device: "{{disk}}"
        label: gpt
        number: 1
        name: root-svrlsiac
        #part_start: 8GiB
        part_end: 100%
        state: present

    - name: Ensure root partition is unmounted
      mount:
        src: /dev/disk/by-partlabel/root-svrlsiac
        path: /mnt
        state: unmounted

    - name: Format root partition
      filesystem:
        dev: /dev/disk/by-partlabel/root-svrlsiac
        fstype: ext4
        force: true

    - name: Mount root partition
      mount:
        src: /dev/disk/by-partlabel/root-svrlsiac
        path: /mnt
        fstype: ext4
        state: ephemeral

    - name: Run pacstrap
      shell:
        chdir: /
        executable: /bin/bash
        cmd: |
          pacstrap -K /mnt base linux linux-firmware ansible

    - name: Run genfstab
      shell:
        chdir: /
        executable: /bin/bash
        cmd: |
          genfstab -U /mnt >> /mnt/etc/fstab

- name: Continue setup in chroot
  hosts: /mnt

  tasks: []
