---
- name: Setup my old retired laptop
  hosts: all

  tasks:

    - name: add hosts to inventory groups
      add_host:
        name: "{{ inventory_hostname }}"
      changed_when: False

    - name: Install required packages
      package:
        name: parted

    - name: Create swap partition
      parted:
        device: "{{disk}}"
        label: gpt
        number: 1
        name: swap-svrlsiac
        part_end: 8GiB
        state: present

    - name: Format swap partition
      filesystem:
        dev: /dev/disk/by-partlabel/swap-svrlsiac
        fstype: swap
        force: true

    - name: Create root partition
      parted:
        device: "{{disk}}"
        label: gpt
        number: 2
        name: root-svrlsiac
        part_start: 8GiB
        part_end: 100%
        state: present

    - name: Format root partition
      filesystem:
        dev: /dev/disk/by-partlabel/root-svrlsiac
        fstype: ext4
        force: true

    - name: Mount root partition
      mount:
        src: /dev/disk/by-partlabel/root-svrlsiac
        path: /mnt
        fstype: ext4
        state: ephemeral
