---
- name: Setup OS
  hosts: isos

  tasks:

    - &prepare_environment
      name: Prepare environment
      block:

        - name: Check if hostname is known
          assert:
            that:
              - hostname in bootstrapparameters

        - name: Decleare bootstrap parameters
          set_fact: { "{{item[0]}}": "{{item[1]}}" }
          loop: "{{bootstrapparameters[hostname].items()}}"

        - name: Check bootstrap parameters
          assert:
            that:
              - bootmode == 'uefi' or bootmode == 'bios'
              - flavor in [ 'debian', 'ubuntu', 'archlinux' ]
              - diskdev is defined and diskdev is string and (diskdev|length) > 0
              - networking in [ 'systemd-networkd', 'network-manager' ]

        - name: Show bootstrap parameters to use
          debug:
            var: |
              {
                'hostname': hostname,
                'bootmode': bootmode,
                'flavor': flavor,
                'diskdev': diskdev,
                'networking': networking,
                'encryptedfs': encryptedfs
              }

    - name: Give the user time to check the shown parameters
      pause:
        seconds: 30

    - name: Set timezone
      timezone:
        name: "{{timezone}}"

    - name: Set locale
      locale_gen:
        name: en_US.UTF-8

    # -> Partition Disk

    - name: Create BIOS boot partition
      parted:
        device: "{{diskdev}}"
        label: gpt
        number: 1
        name: biosboot-svrlsiac
        flags: [ bios_grub ]
        part_end: 8MiB
        state: present
      when: bootmode == 'bios'

    - name: Create UEFI boot partition
      parted:
        device: "{{diskdev}}"
        label: gpt
        number: 1
        name: uefiboot-svrlsiac
        flags: [ esp ]
        part_end: 512MiB
        state: present
      when: bootmode == 'uefi'

    - name: Create boot partition
      parted:
        device: "{{diskdev}}"
        label: gpt
        number: 2
        name: boot-svrlsiac
        part_start: "{{ '512MiB' if bootmode == 'uefi' else '8MiB' }}"
        part_end: '4096MiB'
        state: present

    - name: Create root partition
      parted:
        device: "{{diskdev}}"
        label: gpt
        number: 3
        name: root-svrlsiac
        part_start: "{{ (512 if bootmode == 'uefi' else 8) + 4096 }}MiB"
        part_end: 100%
        state: present

    - name: Encrypt root partition
      community.crypto.luks_device:
        device: "{{'/dev/disk/by-partlabel/root-svrlsiac' | realpath}}"
        label: "root-svrlsiac-luks"
        state: "opened"
        name: "root-svrlsiac-dec"
        passphrase: huhu123
        allow_discards: true
      when: encryptedfs

    - name: Ensure chroot folder
      file:
        path: "{{chrootmountpoint}}"
        owner: root
        group: root
        mode: u=rwx,go=rx
        state: directory

    - name: Ensure chroot is unmounted
      include_role:
        name: chrootsetup
        tasks_from: uninstall
      vars:
        chrootdevice: "{{ '/dev/mapper/root-svrlsiac-dec' if encryptedfs else ('/dev/disk/by-partlabel/root-svrlsiac' | realpath) }}"
        chrootbootdevice: "{{'/dev/disk/by-partlabel/boot-svrlsiac' | realpath}}"
        efibootdevice: "{{ ('/dev/disk/by-partlabel/uefiboot-svrlsiac' | realpath) if bootmode == 'uefi' else '' }}"
        efipath: "{{ '/efi' if flavor == 'archlinux' else '/boot/efi' }}"

    - name: Format UEFI boot partition
      filesystem:
        dev: "{{'/dev/disk/by-partlabel/uefiboot-svrlsiac' | realpath }}"
        fstype: vfat
        force: true
      when: bootmode == 'uefi'

    - name: Format root partition
      filesystem:
        dev: "{{ '/dev/mapper/root-svrlsiac-dec' if encryptedfs else ('/dev/disk/by-partlabel/root-svrlsiac' | realpath) }}"
        fstype: ext4
        force: true

    - name: Mount root partition
      mount:
        src: "{{ '/dev/mapper/root-svrlsiac-dec' if encryptedfs else ('/dev/disk/by-partlabel/root-svrlsiac' | realpath) }}"
        path: "{{chrootmountpoint}}"
        fstype: ext4
        state: ephemeral

    - name: Format boot partition
      filesystem:
        dev: "{{ '/dev/disk/by-partlabel/boot-svrlsiac' | realpath }}"
        fstype: ext4
        force: true

    - name: Mount boot partition
      mount:
        src: "{{ '/dev/disk/by-partlabel/boot-svrlsiac' | realpath }}"
        path: "{{chrootmountpoint}}/boot"
        fstype: ext4
        state: ephemeral

    # -> Bootstrap root filesystem

    - name: Ensure up-to-date archlinux-keyring
      pacman:
        name: archlinux-keyring
        state: latest
        update_cache: true
      when: flavor == 'archlinux'

    - name: Run pacstrap for Arch Linux
      shell:
        chdir: /
        executable: /bin/bash
        cmd: |
          pacstrap -K {{chrootmountpoint}} base linux linux-firmware bash grub efibootmgr
      when: flavor == 'archlinux'

    - name: Run debootstrap for Debian
      shell:
        chdir: /
        executable: /bin/bash
        cmd: |
          debootstrap --variant=minbase --arch amd64 {{codename}} {{chrootmountpoint}} {{debianmirror}}
      when: flavor == 'debian'

    - name: Run debootstrap for Ubuntu
      shell:
        chdir: /
        executable: /bin/bash
        cmd: |
          debootstrap --variant=minbase --no-check-certificate --arch amd64 {{codename}} {{chrootmountpoint}} {{ubuntumirror}}
      when: flavor == 'ubuntu'

    # -> Customizations to make networking work for proxies / corporate CAs

    - name: Ensure environment variables
      shell:
        chdir: /
        executable: /bin/bash
        cmd: |
          cp /etc/environment {{chrootmountpoint}}/etc/environment

    - name: Ensure resolv.conf
      shell:
        chdir: /
        executable: /bin/bash
        cmd: |
          cp /etc/resolv.conf {{chrootmountpoint}}/etc/resolv.conf

    - name: Ensure TLS certificates on Arch Linux systems
      shell:
        chdir: /
        executable: /bin/bash
        cmd: |
          cat /etc/ca-certificates/trust-source/anchors/*.crt >> {{chrootmountpoint}}/etc/ssl/certs/ca-certificates.crt || true
          mkdir -p {{chrootmountpoint}}/etc/ca-certificates/trust-source/anchors
          cp /etc/ca-certificates/trust-source/anchors/*.crt {{chrootmountpoint}}/etc/ca-certificates/trust-source/anchors || true
      when: flavor == 'archlinux'

    - name: Ensure TLS certificates on Debian/Ubuntu systems
      shell:
        chdir: /
        executable: /bin/bash
        cmd: |
          cat /etc/ca-certificates/trust-source/anchors/*.crt >> {{chrootmountpoint}}/etc/ssl/certs/ca-certificates.crt || true
          mkdir -p {{chrootmountpoint}}/usr/local/share/ca-certificates
          cp /etc/ca-certificates/trust-source/anchors/*.crt {{chrootmountpoint}}/usr/local/share/ca-certificates || true
      when: flavor in [ 'debian', 'ubuntu' ]

    # -> Prepare chroot for second stage

    - name: Ensure chroot is mounted
      include_role:
        name: chrootsetup
        tasks_from: install
      vars:
        chrootdevice: "{{ '/dev/mapper/root-svrlsiac-dec' if encryptedfs else ('/dev/disk/by-partlabel/root-svrlsiac' | realpath) }}"
        chrootbootdevice: "{{'/dev/disk/by-partlabel/boot-svrlsiac' | realpath}}"
        efibootdevice: "{{ ('/dev/disk/by-partlabel/uefiboot-svrlsiac' | realpath) if bootmode == 'uefi' else '' }}"
        efipath: "{{ '/efi' if flavor == 'archlinux' else '/boot/efi' }}"

    - name: Generate fstab file
      shell:
        chdir: /
        executable: /bin/bash
        cmd: |
          genfstab -U {{chrootmountpoint}} >> {{chrootmountpoint}}/etc/fstab

    - name: Generate crypttab file
      shell:
        chdir: /
        executable: /bin/bash
        cmd: |
          echo "root-svrlsiac-dec UUID=$(cryptsetup luksDump /dev/disk/by-label/root-svrlsiac-luks | grep UUID | awk '{print $2}') none luks,discard" > {{chrootmountpoint}}/etc/crypttab
      when: flavor in [ 'ubuntu', 'debian' ] and encryptedfs

    # -> Install additional packages to make ansible chroot work

    - name: Update package sources for Debian/Ubuntu systems
      include_role:
        name: sourceslist
        defaults_from: "{{flavor}}-{{codename}}"
      vars:
        sourcesfileprefix: "{{chrootmountpoint}}"
      when: flavor in [ 'ubuntu', 'debian' ]

    - name: Install Ansible in chroot for Arch Linux systems
      shell:
        chdir: /
        executable: /bin/bash
        cmd: |
          chroot {{chrootmountpoint}} /bin/bash -c "pacman --noconfirm --needed -Sy git ansible curl ca-certificates"
      when: flavor == 'archlinux'

    - name: Install Ansible in chroot for Debian/Ubuntu systems
      shell:
        chdir: /
        executable: /bin/bash
        cmd: |
          chroot {{chrootmountpoint}} /bin/bash -c "apt update && apt install -y git ansible curl ca-certificates"
      when: flavor in [ 'debian', 'ubuntu' ]

- name: Continue setup in chroot
  hosts: chroots

  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  tasks:

    - *prepare_environment

    - name: Configure python
      include_role:
        name: pythonsetup

    - name: Create hostname file
      copy:
        dest: /etc/hostname
        owner: root
        group: root
        mode: u=rw,go=r
        content: |
          {{hostname}}

    - name: Create hosts file
      copy:
        dest: /etc/hosts
        owner: root
        group: root
        mode: u=rw,go=r
        content: |
          127.0.0.1        localhost
          ::1              localhost ip6-localhost ip6-loopback
          ff02::1          ip6-allnodes
          ff02::2          ip6-allrouters

    # -> Install additional packages

    - name: Install additional software for Debian/Ubuntu systems
      apt:
        name: "{{additionalpackages}}"
        force_apt_get: true
        update_cache: true
      when: flavor in [ 'ubuntu', 'debian' ]

    - name: Install additional software for Arch Linux systems
      pacman:
        name: "{{additionalpackages}}"
        update_cache: true
      when: flavor == 'archlinux'

    - name: Install Kernel and Bootloader on Ubuntu/Debian systems
      block:

        - name: Install Debian Linux Kernel
          apt:
            name:
              - linux-image-generic
              - linux-headers-generic
              - intel-microcode
              - amd64-microcode
              - firmware-linux
          when: flavor == 'debian'

        - name: Ensure bootloader packages are uninstalled
          apt:
            state: absent
            purge: true
            name:
              - grub2
              - grub-efi
              - os-prober

        - name: Install Ubuntu Linux Kernel
          apt:
            name: linux-generic
          when: flavor == 'ubuntu'

        - name: Install Grub for BIOS on Debian/Ubuntu systems
          apt:
            name: grub2
          when: bootmode == 'bios'

        - name: Install Grub for UEFI on Debian/Ubuntu systems
          apt:
            name: grub-efi
          when: bootmode == 'uefi'

        - name: Install cryptsetup
          apt:
            name:
              - initramfs-tools
              - busybox
              - cryptsetup-initramfs
          when: encryptedfs

      when: flavor in [ 'debian', 'ubuntu' ]

    # -> Localization

    - name: Set locale
      locale_gen:
        name: "{{item}}"
      loop: "{{locales}}"

    - name: Set timezone
      ansible.builtin.file:
        src: /usr/share/zoneinfo/{{timeregion}}/{{timecity}}
        dest: /etc/localtime
        owner: root
        group: root
        state: link
        force: true

    - name: Ensure locales environment variables
      lineinfile:
        path: /etc/environment
        regexp: "{{item.r}}"
        line: "{{item.l}}"
      loop:
        - { r: '^LC_ALL=', l: 'LC_ALL={{locale}}' }
        - { r: '^LANG=', l: 'LANG={{locale}}' }

    - name: Create keyboard configuration for Arch Linux systems
      copy:
        dest: "/etc/vconsole.conf"
        owner: root
        group: root
        mode: u=rw,go=r
        content: |
          KEYMAP={{vconsolekeymap}}
      when: flavor == 'archlinux'

    - name: Keyboard config for Debian/Ubuntu systems
      copy:
        dest: /etc/default/keyboard
        owner: root
        group: root
        mode: u=rw,go=r
        content: |
          XKBMODEL="pc105"
          XKBLAYOUT="{{debconfkeymaplayoutcode}}"
          XKBVARIANT="{{debconfkeymapvariantcode}}"
          XKBOPTIONS="lv3:ralt_switch"
          BACKSPACE="guess"
      when: flavor in [ 'ubuntu', 'debian' ]

    - name: Console-Setup config for Debian/Ubuntu systems
      copy:
        dest: /etc/default/console-setup
        owner: root
        group: root
        mode: u=rw,go=r
        content: |
          ACTIVE_CONSOLES="/dev/tty[1-6]"
          CHARMAP="{{debconfcharmap}}"
          CODESET="{{debconfcodeset}}"
          FONTFACE="{{debconffontface}}"
          FONTSIZE="{{debconffontsize}}"
          VIDEOMODE=
      when: flavor in [ 'ubuntu', 'debian' ]

    - name: Debconf for Debian/Ubuntu systems
      debconf:
        name: "{{item[0]}}"
        question: "{{item[1]}}"
        vtype: "{{item[2]}}"
        value: "{{item[3]}}"
      loop:
        - [ 'keyboard-configuration', 'keyboard-configuration/store_defaults_in_debconf_db', 'boolean', 'true' ]
        - [ 'console-setup', 'console-setup/store_defaults_in_debconf_db', 'boolean', 'true' ]
        - [ 'locales', 'locales/default_environment_locale', 'select', '{{locale}}' ]
        - [ 'locales', 'locales/locales_to_be_generated', 'multiselect', "{{locales|join(' UTF-8, ')}} UTF-8" ]
        - [ 'tzdata', 'tzdata/Zones/Etc', 'select', '{{timeregion}}' ]
        - [ 'tzdata', 'tzdata/Zones/{{timeregion}}', 'select', '{{timecity}}' ]
      when: flavor in [ 'ubuntu', 'debian' ]

    - name: Run dpkg-reconfigure on Debian/Ubuntu systems
      shell:
        chdir: /
        executable: /bin/bash
        cmd: 'dpkg-reconfigure -fnoninteractive {{item}}'
      loop:
        - console-setup
        - keyboard-configuration
        - locales
        - tzdata
      when: flavor in [ 'ubuntu', 'debian' ]

    # -> Root Account

    - name: Set root password
      user:
        name: root
        password: '{{rootpassword}}'
        update_password: always

    - name: Set ssh keys for root account and delete existing if necessary
      authorized_key:
        user: root
        key: "{{rootsshkeys|join('\n')}}"
        exclusive: true

    # -> Bootloader

    - name: Configure verbose boot output in bootloader for Arch Linux
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3"'
      when: flavor == 'archlinux' and not encryptedfs

    - name: Configure verbose boot output and cryptfs in bootloader for Arch Linux
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 cryptdevice=/dev/disk/by-partlabel/root-svrlsiac:root-svrlsiac-dec"'
      when: flavor == 'archlinux' and not encryptedfs

    - name: Add encyption hook to bootloader for Arch Linux
      ansible.builtin.lineinfile:
        path: /etc/mkinitcpio.conf
        regexp: '^HOOKS='
        line: 'HOOKS=(base udev autodetect modconf block encrypt filesystems keyboard fsck)'
      when: flavor == 'archlinuy' and encryptedfs

    - name: Configure verbose boot output in bootloader for Arch Linux
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_ENABLE_CRYPTODISK='
        line: 'GRUB_ENABLE_CRYPTODISK=y'
      when: flavor in [ 'debian', 'ubuntu' ] and encryptedfs

    - name: Install bootloader in BIOS mode for Arch Linux
      shell:
        executable: /bin/bash
        cmd: |
          mkinitcpio -P
          grub-install --target=i386-pc {{diskdev}}
          grub-mkconfig -o /boot/grub/grub.cfg
      when: flavor == 'archlinux' and bootmode == 'bios'

    - name: Install bootloader in UEFI mode for Arch Linux
      shell:
        executable: /bin/bash
        cmd: |
          mkinitcpio -P
          grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=GRUB --recheck --no-nvram --removable {{diskdev}}
          grub-mkconfig -o /boot/grub/grub.cfg
      when: flavor == 'archlinux' and bootmode == 'uefi'

    - name: Install bootloader in BIOS mode for Debian/Ubuntu systems
      shell:
        executable: /bin/bash
        cmd: |
          grub-install --target=i386-pc {{diskdev}}
          update-grub
      when: flavor in [ 'debian', 'ubuntu' ] and bootmode == 'bios'

    - name: Install bootloader in UEFI mode for Debian
      shell:
        executable: /bin/bash
        cmd: |
          grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB --recheck --no-nvram --removable {{diskdev}}
          update-grub
      when: flavor == 'debian' and bootmode == 'uefi'

    - name: Install bootloader in UEFI mode for Ubuntu
      shell:
        executable: /bin/bash
        cmd: |
          grub-install {{diskdev}}
          update-grub
      when: flavor == 'ubuntu' and bootmode == 'uefi'

    # -> Services

    - name: Configure systemd-networkd
      include_role:
        name: networkdsetup
      when: networking == 'systemd-networkd'

    - name: Install and configure network-manager
      include_role:
        name: networkmanagersetup
      vars:
        networkmanager_gui: false
      when: networking == 'network-manager'

    - name: Install services
      apt:
        name:
          - systemd-resolved
          - systemd-timesyncd
      when: flavor in [ 'ubuntu', 'debian' ]

    - name: Enable services
      systemd:
        name: "{{item}}"
        enabled: yes
      loop:
        - systemd-timesyncd
        - systemd-resolved
        - "{{ 'sshd' if flavor == 'archlinux' else 'ssh' }}"

    - name: Configure perrys-ansible-apply
      include_role:
        name: applyscriptsetup
      vars:
        applyscript_service_enabled: "{{firstbootplaybook}}"
