---
- name: Setup my old retired laptop
  hosts: all

  tasks:

    - name: add hosts to inventory groups
      add_host:
        name: "{{ inventory_hostname }}"
      changed_when: False

    - name: Install required packages
      package:
        name: parted

    - name: Create root partition
      parted:
        device: "{{disk}}"
        label: gpt
        number: 1
        name: root
        flags: [ boot ]
        fs_type: ext4
        part_end: -8GiB
        state: present

    - name: Create swap partition
      parted:
        device: "{{disk}}"
        label: gpt
        number: 2
        name: swap
        fs_type: swap
        part_end: 100%
        state: present
