all:
  vars:
    selfrepo: https://github.com/perryflynn/iac.git
    selfbranch: dev

    timezone: Europe/Berlin
    timeregion: Europe
    timecity: Berlin
    locale: en_US.UTF-8
    localelong: en_US.UTF-8 UTF-8
    vconsolekeymap: de-latin1

  children:

    # Bootstrapping Operating Systems

    bootstrap:
      children:

        # I use Arch Linux, btw
        archlinux:
          vars:
            diskdev: /dev/sda
            bootmode: uefi
            flavor: debian
            chrootmountpoint: /mnt
            hostname: mydemoarch
            rootpassword: '$y$j9T$M5rN4LdKH8Xr5oR/hGQjr/$uyqZToLa6YJA0aAXvuFu0AsZAHd50dXw3dw4i7N.Jk.'
            additionalpackages:
              # - ansible
              # - networkmanager
              # - openssh
              # - git
              # - inetutils
              - ansible-core
              - network-manager
              - openssh-server
              - git
              - net-tools
              - dnsutils
          hosts:
            archiso:
            /mnt:
              ansible_connection: chroot

    # Configure Operating Systems

    configuration:
      hosts:

        # retired Thinkpad X230 Laptop
        mydemoarch:
