all:
  vars:
    selfrepo: https://github.com/perryflynn/iac.git
    selfbranch: dev
    selfapplyscript: /usr/local/sbin/perrys-ansible-apply.sh

    timezone: Europe/Berlin
    timeregion: Europe
    timecity: Berlin
    locale: en_US.UTF-8
    localelong: en_US.UTF-8 UTF-8
    vconsolekeymap: de-latin1
    vconsolekeymapvariant: deadactute
    xfcekeymap: de
    xfcekeymapvariant: deadactute

    rootpassword: '$y$j9T$M5rN4LdKH8Xr5oR/hGQjr/$uyqZToLa6YJA0aAXvuFu0AsZAHd50dXw3dw4i7N.Jk.'
    rootsshkeys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHqrQkBwBaMTfN0vHvW6aldKK9MBd8X7GyiaMWLczdNo christian@kompaktes2k'

    username: christian
    userpassword: '$y$j9T$M5rN4LdKH8Xr5oR/hGQjr/$uyqZToLa6YJA0aAXvuFu0AsZAHd50dXw3dw4i7N.Jk.'
    usergroups: [ adm, games, audio, optical, storage, network, sudo ]
    usersshkeys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHqrQkBwBaMTfN0vHvW6aldKK9MBd8X7GyiaMWLczdNo christian@kompaktes2k'

  children:

    isos:
      hosts:
        archlinuxiso:
        debianiso:
        ubuntuiso:

    chroots:
      hosts:
        /mnt/archlinux:
        /mnt/debian:
        /mnt/ubuntu:

    # Bootstrapping Operating Systems

    bootstrap:
      vars:
        # parameters by target systems hostname
        bootstrapparameters:
          retired:
            bootmode: uefi
            diskdev: /dev/sda
          biostest:
            bootmode: bios
            diskdev: /dev/sda
          uefitest:
            bootmode: uefi
            diskdev: /dev/sda

      children:

        # I use Arch Linux, btw
        bootstrap-archlinux:
          vars:
            flavor: archlinux
            chrootmountpoint: /mnt/archlinux
            hostname: mydemoarch
            additionalpackages:
              #- networkmanager
              - openssh
              - inetutils
              - net-tools
              - dnsutils
              - gnupg
              - iputils
              - iproute2
              - vim
              - nano
              - dialog
              - man-db
          hosts:
            archlinuxiso:
            /mnt/archlinux:
              ansible_connection: chroot

        # Debian is also okay
        bootstrap-debian:
          vars:
            flavor: debian
            codename: bookworm
            chrootmountpoint: /mnt/debian
            hostname: mydemodebian
            additionalpackages: &debian_packages
              #- network-manager
              - openssh-server
              - net-tools
              - dnsutils
              - gnupg
              - iputils-ping
              - iproute2
              - util-linux-extra
              - locales
              - console-setup
              - keyboard-configuration
              - vim
              - nano
              - dialog
              - man-db
          hosts:
            debianiso:
            /mnt/debian:
              ansible_connection: chroot

        # So is Ubuntu...
        bootstrap-ubuntu:
          vars:
            flavor: ubuntu
            codename: noble
            chrootmountpoint: /mnt/ubuntu
            hostname: mydemoubuntu
            additionalpackages: *debian_packages
          hosts:
            ubuntuiso:
            /mnt/ubuntu:
              ansible_connection: chroot

    # Configure Operating Systems

    configuration:
      hosts:

        # Default hostnames
        mydemoarch:
        mydemodebian:
        mydemoubuntu:

        uefitest:
        biostest:

        # retired Thinkpad X230 Laptop
        retired:
          wallpaper: dragonfly.jpg
