all:
  vars:
    timezone: Europe/Berlin
    timeregion: Europe
    timecity: Berlin
    locale: en_US.UTF-8
    localelong: en_US.UTF-8 UTF-8
    vconsolekeymap: de-latin1

  children:

    # Bootstrapping Operating Systems

    bootstrap:
      children:

        # I use Arch Linux, btw

        archlinux:
          vars:
            diskdev: /dev/sda
            chrootmountpoint: /mnt
            hostname: mydemoarch
            rootpassword: '$y$j9T$M5rN4LdKH8Xr5oR/hGQjr/$uyqZToLa6YJA0aAXvuFu0AsZAHd50dXw3dw4i7N.Jk.'
          hosts:
            archiso:
            /mnt:
              ansible_connection: chroot
