all:
  vars:
    selfrepo: https://github.com/perryflynn/iac.git
    selfbranch: dev
    selfapplyscript: /usr/local/sbin/perrys-ansible-apply.sh

    ubuntumirror: http://de.archive.ubuntu.com/ubuntu/
    debianmirror: http://deb.debian.org/debian/

    timezone: Europe/Berlin
    timeregion: Europe
    timecity: Berlin

    locale: &mainlocale en_US.UTF-8
    locales:
      - *mainlocale
      - de_DE.UTF-8
    localelong: en_US.UTF-8 UTF-8

    vconsolekeymap: de-latin1
    vconsolekeymapvariant: deadacute

    xfcekeymap: de
    xfcekeymapvariant: deadacute

    debconfkeymaplayoutcode: de
    debconfkeymapvariantcode: deadacute
    debconfcharmap: UTF-8
    debconfcodeset: Lat15
    debconffontface: VGA
    debconffontsize: 8x16

    rootpassword: '$y$j9T$M5rN4LdKH8Xr5oR/hGQjr/$uyqZToLa6YJA0aAXvuFu0AsZAHd50dXw3dw4i7N.Jk.'
    rootsshkeys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHqrQkBwBaMTfN0vHvW6aldKK9MBd8X7GyiaMWLczdNo christian@kompaktes2k'

    username: christian
    userpassword: '$y$j9T$M5rN4LdKH8Xr5oR/hGQjr/$uyqZToLa6YJA0aAXvuFu0AsZAHd50dXw3dw4i7N.Jk.'
    usergroups: [ adm, games, audio, optical, storage, network, sudo ]
    usersshkeys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHqrQkBwBaMTfN0vHvW6aldKK9MBd8X7GyiaMWLczdNo christian@kompaktes2k'

  children:

    isos:
      hosts:
        archlinuxiso:
        debianiso:
        ubuntuiso:

    chroots:
      hosts:
        /mnt/archlinux:
        /mnt/debian:
        /mnt/ubuntu:

    # Bootstrapping Operating Systems

    bootstrap:
      vars:
        # parameters by target systems hostname
        bootstrapparameters:
          retired:
            bootmode: uefi
            diskdev: /dev/sda
            firstbootplaybook: true
            networking: network-manager
          debidesk:
            bootmode: bios
            diskdev: /dev/sda
            firstbootplaybook: false
            networking: systemd-networkd
          biostest:
            bootmode: bios
            diskdev: /dev/sda
            firstbootplaybook: false
            networking: systemd-networkd
          uefitest:
            bootmode: uefi
            diskdev: /dev/sda
            firstbootplaybook: false
            networking: systemd-networkd

      children:

        # I use Arch Linux, btw
        bootstrap_archlinux:
          vars:
            flavor: archlinux
            chrootmountpoint: /mnt/archlinux
            hostname: biostest
            additionalpackages:
              - openssh
              - inetutils
              - net-tools
              - dnsutils
              - gnupg
              - iputils
              - iproute2
              - curl
              - wget
              - vim
              - nano
              - dialog
              - man-db
              - rxvt-unicode-terminfo
              - wezterm-terminfo
          hosts:
            archlinuxiso:
            /mnt/archlinux:
              ansible_connection: chroot

        # Debian is also okay
        bootstrap_debian:
          vars:
            flavor: debian
            codename: bookworm
            chrootmountpoint: /mnt/debian
            hostname: biostest
            additionalpackages: &debian_packages
              - openssh-server
              - net-tools
              - dnsutils
              - gnupg
              - iputils-ping
              - iproute2
              - curl
              - wget
              - util-linux-extra
              - locales
              - console-setup
              - keyboard-configuration
              - vim
              - nano
              - dialog
              - man-db
              - debconf-utils
              - terminfo
          hosts:
            debianiso:
            /mnt/debian:
              ansible_connection: chroot

        bootstrap_debiankvm:
          vars:
            flavor: debian
            codename: bookworm
            chrootmountpoint: /mnt/debiankvm
            hostname: biostest
            additionalpackages:
              - openssh-server
              - net-tools
              - dnsutils
              - gnupg
              - iputils-ping
              - iproute2
              - curl
              - wget
              - util-linux-extra
              - locales
              - console-setup
              - keyboard-configuration
              - vim
              - nano
              - dialog
              - man-db
              - debconf-utils
              - terminfo
              - qemu-guest-agent
          hosts:
            debiankvmiso:
            /mnt/debiankvm:

        # So is Ubuntu...
        bootstrap_ubuntu:
          vars:
            flavor: ubuntu
            codename: noble
            chrootmountpoint: /mnt/ubuntu
            hostname: biostest
            additionalpackages: *debian_packages
          hosts:
            ubuntuiso:
            /mnt/ubuntu:
              ansible_connection: chroot

    # Configure Operating Systems

    configuration:
      hosts:

        # Default hostnames
        uefitest:
        biostest:

        # retired Thinkpad X230 Laptop
        retired:
          wallpaper: dragonfly.jpg

        debidesk:
