all:
  vars:
    selfrepo: https://github.com/perryflynn/iac.git
    selfbranch: dev

    timezone: Europe/Berlin
    timeregion: Europe
    timecity: Berlin
    locale: en_US.UTF-8
    localelong: en_US.UTF-8 UTF-8
    vconsolekeymap: de-latin1

    rootpassword: '$y$j9T$M5rN4LdKH8Xr5oR/hGQjr/$uyqZToLa6YJA0aAXvuFu0AsZAHd50dXw3dw4i7N.Jk.'

  children:

    isos:
      hosts:
        archlinuxiso:
        debianiso:

    chroots:
      hosts:
        /mnt/archlinux:
        /mnt/debian:

    # Bootstrapping Operating Systems

    bootstrap:
      children:

        # I use Arch Linux, btw
        bootstrap-archlinux:
          vars:
            diskdev: /dev/sda
            bootmode: uefi
            flavor: archlinux
            chrootmountpoint: /mnt/archlinux
            hostname: mydemoarch
            additionalpackages:
              - ansible
              - networkmanager
              - openssh
              - git
              - inetutils
              - net-tools
              - dnsutils
              - curl
              - ca-certificates
              - gnupg
              - iputils
              - iproute2
          hosts:
            archlinuxiso:
            /mnt/archlinux:
              ansible_connection: chroot

        # Debian is also okay
        bootstrap-debian:
          vars:
            diskdev: /dev/sda
            bootmode: uefi
            flavor: debian
            chrootmountpoint: /mnt/debian
            hostname: mydemodebian
            additionalpackages:
              - ansible
              - network-manager
              - openssh-server
              - git
              - net-tools
              - dnsutils
              - curl
              - ca-certificates
              - gnupg
              - iputils-ping
              - iproute2
          hosts:
            debianiso:
            /mnt/debian:
              ansible_connection: chroot

    # Configure Operating Systems

    configuration:
      hosts:

        # retired Thinkpad X230 Laptop
        mydemoarch:
