---
# roles/pulseaudiosetup/tasks/main.yml

- name: Ensure parameters
  assert:
    that:
      - ansible_distribution == 'Archlinux'

- name: Install pulseaudio
  package:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - pamixer
      - pulsemixer
      - pavucontrol
