---
# roles/bluetoothsetup/tasks/main.yml

- name: Ensure parameters
  assert:
    that:
      - ansible_distribution == 'Archlinux'

- name: Install pulseaudio
  package:
    name:
      - bluez
      - bluez-utils
      - blueman
