---
# roles/selfsignedcert/tasks/main.yml

- name: Ensure parameters
  assert:
    that:
      - ansible_distribution in [ 'Archlinux', 'Debian', 'Ubuntu' ]

- name: Install python dependencies
  pip:
    name: cryptography

- name: Create private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{selfsigned_keypath}}"
    type: RSA
    size: 4096
    owner: root
    group: root
    mode: u=rw,g=r,o=-

- name: Create SAN list
  set_fact:
    newsanlist: "{{ ([selfsigned_name]+selfsigned_names) | map('regex_replace', '^', 'DNS:') }}"

- name: Create certificate signing request (CSR) for self-signed certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{selfsigned_keypath}}"
    country_name: DE
    locality_name: Lower Saxony
    organization_name: IAC
    organizational_unit_name: Perrys Ansible Apply
    email_address: no-reply@example.com
    common_name: "{{selfsigned_name}}"
    subject_alt_name: "{{newsanlist}}"
  register: csr

- name: Create self-signed certificate from CSR
  community.crypto.x509_certificate:
    path: "{{selfsigned_certpath}}"
    csr_content: "{{csr.csr}}"
    privatekey_path: "{{selfsigned_keypath}}"
    provider: selfsigned
    owner: root
    group: root
    mode: u=rw,go=r

- name: Copy certificate into trust store for Arch Linux systems
  copy:
    remote_src: true
    src: "{{selfsigned_certpath}}"
    dest: "/etc/ca-certificates/trust-source/anchors/{{selfsigned_certpath|basename}}"
    owner: root
    group: root
    mode: u=rw,go=r
  when: ansible_distribution == 'Archlinux'

- name: Regenerate trust store for Arch Linuy systems
  shell:
    chdir: /
    executable: /bin/bash
    cmd: |
      update-ca-trust
  when: ansible_distribution == 'Archlinux'

- name: Copy certificate into trust store for Debian/Ubuntu systems
  copy:
    remote_src: true
    src: "{{selfsigned_certpath}}"
    dest: "/usr/local/share/ca-certificates/{{selfsigned_certpath|basename}}"
    owner: root
    group: root
    mode: u=rw,go=r
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- name: Regenerate trust store for Debian/Ubuntu systems
  shell:
    chdir: /
    executable: /bin/bash
    cmd: |
      update-ca-certificates
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
