---
# roles/chrootsetup/tasks/install.yml

- name: Validate parameters
  assert:
    that:
      - chrootmountpoint is directory
      - chrootdevice is link or chrootdevice is file

- name: Mount root partition
  mount:
    src: "{{chrootdevice}}"
    path: "{{chrootmountpoint}}"
    fstype: ext4
    state: ephemeral

- name: Mount proc
  mount:
    src: none
    path: "{{chrootmountpoint}}/proc"
    fstype: proc
    state: ephemeral

- name: Mount sys
  mount:
    path: "{{chrootmountpoint}}/sys"
    src: /sys
    opts: bind
    state: ephemeral
    fstype: none

- name: Mount dev
  mount:
    path: "{{chrootmountpoint}}/dev"
    src: /dev
    opts: bind
    state: ephemeral
    fstype: none
