---
# roles/nginxuserserver/tasks/main.yml

- name: Ensure parameters
  assert:
    that:
      - ansible_distribution == 'Archlinux'

- name: Install NGINX
  package:
    name:
      - nginx
      - nginx-mod-headers-more
