---
# roles/xfcesetup/tasks/main.yml

- name: Ensure parameters
  assert:
    that:
      - ansible_distribution == 'Archlinux'

- name: Install Desktop Environment
  package:
    name:
      - xfce4
      - xfce4-goodies
      - adobe-source-sans-fonts
      - adobe-source-serif-fonts
      - noto-fonts
      - gnu-free-fonts
      - ttf-dejavu
      - ttf-dejavu-nerd
      - ttf-droid
      - ttf-liberation
      - ttf-ubuntu-font-family

- name: Configure xfce
  xfconf:
    channel: "{{item.c}}"
    property: "{{item.p}}"
    value_type: "{{item.t}}"
    value: "{{item.v}}"
    force_array: "{{item.a}}"
  loop:
    - { c: keyboard-layout, p: /Default/XkbDisable, a: false, t: bool, v: 'false' }
    - { c: keyboard-layout, p: /Default/XkbLayout, a: true, t: string, v: [ de, en ] }
  become: true
  become_user: christian
